### ISSUE TITLE
Is the -flags option in the README tutorial necessary?

### ISSUE THREAD

**Issue by XwanXuanX** [eisopux/javac-diagnostics-wrapper#127]
I've setup the environment according to the README and everything worked fine.

However, when I tried to run the program with this command:
`java -cp /Users/yetong_li/Documents/UW/URA/javac-diagnostics-wrapper/build/libs/javac-diagnostics-wrapper-all.jar io.github.wmdietl.diagnostics.json.lsp.Main -flags testfile.java`
I encountered an error as follows:
`Invalid options: recognizedOptions = []; classNames = []; files = [testfile.java]; unrecognizedOptions = [-flags]`

Then I tried to remove the `-flags` option, it works.

So what's the purpose of this `-flags` option in README? Should it be removed?

Thanks!

**Comment by wmdietl** [comment]
Thanks for the report @XwanXuanX !

I think the `-flags` is meant as a stand-in for whatever actual javac flags you're using.
This should be made explicit and illustrated with a concrete example.
Can you prepare a PR that improves this?

**Comment by XwanXuanX** [comment]
Hi @wmdietl, this issue is addressed in an open PR.
